// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import ActionFormsController from "controllers/action_forms_controller"
application.register("action-forms", ActionFormsController)

import AutoSubmitController from "controllers/auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import CheckoutFormController from "controllers/checkout_form_controller"
application.register("checkout-form", CheckoutFormController)

import ExpandableCardController from "controllers/expandable_card_controller"
application.register("expandable-card", ExpandableCardController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import LoginMethodController from "controllers/login_method_controller"
application.register("login-method", LoginMethodController)

import ToastController from "controllers/toast_controller"
application.register("toast", ToastController)

import VisitorCardController from "controllers/visitor_card_controller"
application.register("visitor-card", VisitorCardController)
